[package]
name = "surveyor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
quickcheck = "1"
semver = "1.0.16"
#rustfmt-nightly = "1.4.21"
